---
image: opendatacube/k8s-dev

options:
  docker: true

definitions:
  services:
    docker:
      memory: 6000

pipelines:
  default:
    - step:
        name: Build and push docker image (nonprod)
        size: 2x
        deployment: test
        script:
          # Construct the version tag
          - VERSION=$(git describe --tags --always)
          - docker build -t geoscienceaustralia/dea-wagl-docker:$VERSION -t geoscienceaustralia/dea-wagl-docker:latest .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_TOKEN
          - docker push geoscienceaustralia/dea-wagl-docker
