---
image: opendatacube/k8s-dev

options:
  docker: true

pipelines:
  default:
    - step:
        name: Build and push docker image (nonprod)
        caches:
          - docker
        deployment: test
        script:
          # Construct the version tag
          - VERSION="poc-$BITBUCKET_BUILD_NUMBER"
          - docker build -t opendatacube/dea-wagl-docker:$VERSION -f overlay/Dockerfile.poc .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push opendatacube/dea-wagl-docker:$VERSION