[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[project]
requires-python = ">=3.6"

[tool.black]
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
include = '\.pyi?$'
line-length = 90
target-version = ['py36', 'py37', 'py38']

[tool.ruff]
line-length = 90
# Which checkers to enable?
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP",  # pyupgrade
    "N"  # pep8-naming
]
target-version = "py38"

[tool.setuptools_scm]
version_scheme = "post-release"
write_to = "eugl/version.py"
