target_version: "20220426-s2-c3"
target_modules_repo: "/g/data/up71/modules"
dea_env_version: "20200612"
dea_version: "20200617"
python_version: "python3.6"
wagl_version: "wagl-5.8.0"
eod1_version: "eodatasets-0.12"
eod3_version: "s2-cloudless"
tesp_version: "tesp-0.11.0"
swfo_version: "swfo-0.0.2"
eugl_version: "eugl-0.5.1"
gost_version: "gost-0.0.3"
modtran_version: "6.0.1"
