target_version: "20220608-s2-c3"
target_modules_repo: "/g/data/up71/modules"
dea_env_version: "20200612"
dea_version: "20200617"
python_version: "python3.6"
wagl_version: "wagl-5.8.4"
eod1_version: "eodatasets-0.12"
eod3_version: "eodatasets3-0.27.3"
tesp_version: "tesp-0.14.1"
swfo_version: "swfo-0.0.2"
eugl_version: "eugl-0.5.2"
gost_version: "gost-0.0.3"
modtran_version: "6.0.1"
