target_version: "20220321-s2-c3"
target_modules_repo: "/g/data/up71/modules"
dea_env_version: "20200612"
dea_version: "20200617"
python_version: "python3.6"
wagl_version: "develop"
eod1_version: "eodatasets-0.12"
eod3_version: "eodatasets3-0.26.1"
tesp_version: "master"
swfo_version: "swfo-0.0.2"
eugl_version: "master"
gost_version: "gost-0.0.3"
modtran_version: "6.0.1"
