apiVersion: batch/v1
kind: Job
metadata:
  name: mod6-test
  namespace: processing
spec:
  template:
    spec:
      containers:
        - name: mod6
          image: uchchwhash/mod6:test
          command: ["/modtran_runner/modtran_runner.sh"]
          volumeMounts:
            - name: wagl-nrt-ancillary-volume
              mountPath: /ancillary
          env:
            - name: MODTRAN_DATA
              value: /ancillary/MODTRAN6.0.2.3G/DATA
            - name: MOD6
              value: /ancillary/MODTRAN6.0.2.3G/bin/linux/mod6c_cons
          envFrom:
            - secretRef:
                name: modtran-key
            - secretRef:
                name: wagl-nrt-aws-creds
      volumes:
        - name: wagl-nrt-ancillary-volume
          persistentVolumeClaim:
            claimName: wagl-nrt-ancillary-volume
      restartPolicy: Never
  backoffLimit: 4
  parallelism: 4
