target_version: "20230306-l9"
target_modules_repo: "/g/data/up71/modules"
dea_env_version: "20200612"
dea_version: "20200617"
python_version: "python3.6"
eod3_version: "0.29.2"
wagl_version: "wagl-5.9.0"
tesp_version: "tesp-0.14.2"
swfo_version: "swfo-0.0.2"
eugl_version: "eugl-0.6.1"
gost_version: "gost-0.0.3"
modtran_version: "6.0.1"
