version: "3.4"
services:
  wagl:
    build:
      context: .
    environment:
      - MODTRAN_PRODUCT_KEY
      - MODTRAN_DATA=/modtran6/MODTRAN6.0/DATA
    volumes:
      - /home/ubuntu/projects/modtran6:/modtran6
      - ./tests/:/tests
