apiVersion: batch/v1
kind: Job
metadata:
  name: mod6-test
  namespace: processing
spec:
  template:
    spec:
      containers:
        - name: mod6
          image: 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com/dev/mod6:test-20210313
          command: ["/modtran_runner/modtran_runner.sh"]
          volumeMounts:
            - name: wagl-nrt-ancillary-volume
              mountPath: /modtran6
          env:
            - name: MODTRAN_DATA
              value: /modtran6/MODTRAN6.0/DATA
          envFrom:
            - secretRef:
                name: mod6-key
            - secretRef:
                name: wagl-nrt-aws-creds
      volumes:
        - name: wagl-nrt-ancillary-volume
          persistentVolumeClaim:
            claimName: wagl-nrt-ancillary-volume
      restartPolicy: Never
  backoffLimit: 4
  parallelism: 4
