name: Docker Tests
on: [push, pull_request]

jobs:
    build-with-docker:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: docker/setup-buildx-action@v2
        -   uses: docker/build-push-action@v4
            with:
                context: .
                load: true
                tags: ard:test
                cache-from: type=gha
                cache-to: type=gha,mode=max
        -   name: Test
            run: docker run --rm -v ${{ github.workspace }}/tests:/tests -w /tests ard:test pytest
