name: Docker Tests
on: [push, pull_request]

jobs:
    build-with-docker:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: docker/setup-buildx-action@v2
        -   uses: docker/build-push-action@v4
            with:
                context: .
                load: true
                tags: ard:dev
                cache-from: type=gha
                cache-to: type=gha,mode=max
        -   name: Test
            run: docker run --rm -v ${{ github.workspace }}/tests:/tests -w /tests ard:dev pytest
        -   uses: docker/login-action@v3
            if: |
                github.event_name == 'push'
                && github.ref == 'refs/heads/main'
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
        -   uses: docker/build-push-action@v4
            if: |
                github.event_name == 'push'
                && github.ref == 'refs/heads/main'
            with:
                context: .
                push: true
                tags: geoscienceaustralia/ard-pipeline:dev
